aids_jiance/article/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # 全部文章列表
    url(regex=r'^$', view=views.AllArticleList.as_view(), name='category_list'),
    # 分类文章列表
    url(regex=r'^(?P<pk>\d+)/$', view=views.CategoryArticleList.as_view(), name='article_list'),
    # 文章详情页
    url(regex=r'^(?P<cid>\d+)_(?P<slug>\w+)$', view=views.ArticleDetailView.as_view(), name='article_detail')
]

aids_jiance/shizhi/urls.py
from django.conf.urls import url

from aids_jiance.shizhi import views

urlpatterns = [
    url(regex=r'^$', view=views.index, name='shizhi'),
    url(regex=r'^(?P<bianhao>\w+)$', view=views.IntroView.as_view(), name='shizhi_intro'),
    url(regex=r'^(?P<bianhao>\w+)/questions/$', view=views.QuestionsView.as_view(), name='shizhi_questions')
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
                  url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                  url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),

                  url(r'^zice/$', TemplateView.as_view(template_name='pages/zice.html'), name='zice'),
                  url(r'^shiyong/$', TemplateView.as_view(template_name='pages/shizhishiyong.html'), name='shiyong'),

                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, admin.site.urls),

                  # Your stuff: custom urls includes go here
                  url(r'^a/', include('aids_jiance.article.urls', namespace='article')),
                  url(r'^shizhi/', include('aids_jiance.shizhi.urls')),

                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

aids_jiance/article/models.py
import hashlib
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User

from django.contrib.sites.models import Site
from django.db import models
# Create your models here.
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import force_bytes, force_str, force_text



def md5_slug(s):
    s = force_bytes(s)
    return hashlib.md5(s).hexdigest()[8:-8]


class ArticleCategory(models.Model):
    name = models.CharField(max_length=20)
    slug = models.TextField(max_length=16, editable=False, unique=True)
    is_nav = models.BooleanField(verbose_name='是否在nav显示', default=False)

    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = '文章分类'

    def get_absolute_url(self):
        return reverse('article:article_list', args=[self.id])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.slug:
            self.slug = md5_slug(self.name)
        super(ArticleCategory, self).save(force_insert=False, force_update=False, using=None,
                                          update_fields=None)

    def __str__(self):
        return self.name

class StatusManager(models.Manager):
    # def get_queryset(self):
    #     return super(StatusManager, self).get_queryset().filter(status='published')
    def published(self):
        return self.get_queryset().filter(status='published')
class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', '草稿'),
        ('published', '发布'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    category = models.ForeignKey(ArticleCategory, related_name='article', verbose_name='文章分类')
    name = models.CharField(max_length=255, verbose_name='文章名')
    slug = models.TextField(max_length=16, editable=False, unique=True)

    # author = models.ForeignKey(User, related_name='aritlce', verbose_name='作者')

    body = RichTextUploadingField(verbose_name='正文')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    stick = models.BooleanField(verbose_name='是否置顶', default=False)
    views = models.PositiveIntegerField(default=5268, verbose_name='阅读统计量')

    seo_key = models.CharField(max_length=200, verbose_name='关键词', null=True, blank=True)
    seo_desc = models.CharField(max_length=255, verbose_name='页面描述', null=True, blank=True)

    objects = StatusManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = '文章'
        verbose_name_plural = '文章'

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.category.id, self.slug])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.slug:
            self.slug = md5_slug(self.name)
        super(Article, self).save(force_insert=False, force_update=False, using=None,
                                  update_fields=None)

    def add_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.name

    @classmethod
    def get_stick(cls):
        return cls.objects.published().all()[:6]

aids_jiance/shizhi/models.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse

# class ShizhiType(models.Model):
#     name = models.CharField(max_length=200, verbose_name='试纸类型')
#     slug = models.CharField(max_length=20)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = '试纸类型'
#         verbose_name_plural = '试纸类型'

class Shizhi(models.Model):
    name = models.CharField(max_length=200, verbose_name='试纸名称')
    bianhao = models.CharField(max_length=6, verbose_name='试纸编号', unique=True)

    cover = models.ImageField(verbose_name='封面图', upload_to='shizhi', null=True, blank=True)
    cover_url = models.URLField(verbose_name='封面图URL', blank=True)

    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = RichTextUploadingField(verbose_name='试纸介绍')

    seo_key = models.CharField(max_length=200, verbose_name='关键词', null=True, blank=True)
    seo_desc = models.CharField(max_length=255, verbose_name='页面描述', null=True, blank=True)

    TYPE_CHOICES = (
        ('xueye', '血液'),
        ('tuoye', '唾液'),
    )
    shizhi_type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='xueye')
    FANGAN_CHOICES = (
        ('danfen', '单份试纸'),
        ('two-week', '两周检测方案'),
        ('four-week', '四周检测方案'),
        ('eight-week', '八周以上检测方案'),
    )
    fangan = models.CharField(max_length=10, choices=FANGAN_CHOICES, default='danfen')
    is_taozhuang = models.BooleanField(default=False, verbose_name='是否是套装')
    other = RichTextField(verbose_name='其他信息', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '试纸'
        verbose_name_plural = '试纸'

    def get_absolute_url(self):
        return reverse('shizhi_intro', args=[self.bianhao])

    def get_questions_url(self):
        return reverse('shizhi_questions', args=[self.bianhao])

    @classmethod
    def get_fangan(cls, k):
        return cls.objects.filter(fangan=k).all()


class Questions(models.Model):
    shizhi = models.ForeignKey('Shizhi')
    name = models.CharField(max_length=200, verbose_name='问题')
    reply = RichTextUploadingField(verbose_name='答案')

    seo_key = models.CharField(max_length=200, verbose_name='关键词', null=True, blank=True)
    seo_desc = models.CharField(max_length=255, verbose_name='页面描述', null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '问答'
        verbose_name_plural = '问答'

    def get_absolute_url(self):
        return reverse('shizhi_questions', args=[self.shizhi.slug])

aids_jiance/site/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.sites.models import Site
from django.db import models


class ExtendSite(models.Model):
    site = models.OneToOneField(Site, related_name='extend')
    logo = models.ImageField(upload_to='logo', null=True, blank=True)

    seo_title = models.CharField(max_length=200, verbose_name='首页标题', blank=True)
    seo_key = models.CharField(max_length=200, verbose_name='首页关键词', blank=True)
    seo_desc = models.CharField(max_length=255, verbose_name='首页页面描述', blank=True)

    analytics = models.TextField(max_length=40, blank=True, verbose_name='统计代码')
    zice = RichTextUploadingField(verbose_name='自测症状持续添加', blank=True)
    shiyong = RichTextUploadingField(verbose_name='试纸使用方法', blank=True)

    def __str__(self):
        return self.site.name

    class Meta:
        verbose_name = 'SIte 扩展'
        verbose_name_plural = 'SIte 扩展'


class Ad(models.Model):
    site = models.OneToOneField(Site, related_name='ad')
    ad1 = models.TextField()
    ad2 = models.TextField()
    ad3 = models.TextField()
    ad4 = models.TextField()
    ad5 = models.TextField()
    ad6 = models.TextField()

    class Meta:
        verbose_name = '广告'
        verbose_name_plural = '广告'

    def __str__(self):
        return '页面广告'

class FriendLink(models.Model):
    site = models.ForeignKey(Site, related_name='friendlink', null=True)
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    logo = models.ImageField(upload_to='friendlink/', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'

aids_jiance/article/views.py
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import ListView, DetailView

from .models import Article, ArticleCategory


class CategoryArticleList(ListView):
    model = Article
    template_name = 'article/article_list.html'
    paginate_by = 15

    def get_queryset(self):
        category = get_object_or_404(ArticleCategory, pk=self.kwargs.get('pk'))
        setattr(self, 'category', category)
        return super(CategoryArticleList, self).get_queryset().filter(category=category)

    def get_context_data(self, **kwargs):
        context = super(CategoryArticleList, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_detail.html'

    def get_object(self, queryset=None):
        cid = self.kwargs.get('cid')
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Article, category_id=cid, slug=slug)
        return obj

    def get(self, request, *args, **kwargs):
        response = super(ArticleDetailView, self).get(request, *args, **kwargs)
        self.object.add_views()
        return response


class AllArticleList(ListView):
    model = Article
    paginate_by = 20
    template_name = 'article/all_article_list.html'

aids_jiance/shizhi/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView
from .models import Shizhi, Questions


def index(request):
    # 试纸首页，试纸套装
    return render(request, 'shizhi/index.html')

class IntroView(DetailView):
    model = Shizhi
    template_name = 'shizhi/intro.html'
    slug_url_kwarg = 'bianhao'
    slug_field = 'bianhao'


class QuestionsView(ListView):
    model = Questions
    template_name = 'shizhi/questions.html'
    paginate_by = 15



    def get_queryset(self):
        shizhi = get_object_or_404(Shizhi, bianhao=self.kwargs.get('bianhao'))
        setattr(self, 'shizhi', shizhi)
        return super(QuestionsView, self).get_queryset().filter(shizhi=shizhi)

    def get_context_data(self, **kwargs):
        context = super(QuestionsView, self).get_context_data(**kwargs)
        context['shizhi'] = self.shizhi
        return context

aids_jiance/templates/shizhi/fangan.html
<table class="table table-bordered table-sm">
    <th>编号</th>
    <th>试纸</th>
    <th>价格</th>
    {% for object in objects %}
        <tr>
            <td>
                <a href="{{ object.get_absolute_url }}">{{ object.bianhao|upper }}</a></td>
            <td>
                <a href="{{ object.get_absolute_url }}">
                    {{ object.name }}
                </a>
            </td>
            <td><i class="fa fa-jpy text-danger" aria-hidden="true"></i>{{ object.price }}</td>

        </tr>
        <tr>
            <td colspan="3">
                {% if not object.is_taozhuang %}
                <span class="text-info">{{ object.get_shizhi_type_display }}试纸</span>
                {% endif %}

                {{ object.other }}
            </td>
        </tr>

    {% endfor %}
</table>

aids_jiance/templates/shizhi/fangan_list.html
<ul class="list-group">
    <li class="list-group-item list-group-item-light">
        {{ v }}
    </li>
    {% for object in objects %}
        <li class="list-group-item">
            <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
        </li>
    {% endfor %}
</ul>

aids_jiance/templates/shizhi/index.html
{% extends 'layout.html' %}
{% load fangan %}

{% block main %}
    <div class="bg-white p-2 mb-2">
        <ul class="nav nav-pills nav-fill mb-2" role="tablist">

            {% for k,v in fangan %}
                <li class="nav-item">
                    <a href="#{{ k }}" class="nav-link {% if forloop.first %}active{% endif %}" id="{{ k }}-tab"
                       data-toggle="tab" role="tab" aria-controls="{{ k }}" aria-selected="true"
                    >{{ v }}</a>
                </li>
            {% endfor %}

        </ul>
        <div class="tab-content" id="jiance-content">
            {% for k, v  in fangan %}
                <div class="tab-pane fade {% if forloop.first %}show active{% endif %}"
                     id="{{ k }}" role="tabpanel" aria-labelledby="{{ k }}-tab">
                    {% fangan k %}
                </div>
            {% endfor %}

        </div>

        <p class="text-danger">Tip:近来有好多人购买试纸一味追求价格，认为价格高的试纸准确度高，这种想法走进了误区，现在为大家解释一下。
            试纸价格不是越贵越好，试纸价格不同是由于检测方法，进口或国产等原因决定的！<br>
            <span class="text-info">
                唾液试纸价格>血液试纸
            </span><br>
            <span class="text-info">
                进口试纸价格>国产试纸
            </span>
        </p>

        <dl>
            <dt>关于两周检测试纸方案为空的说明：</dt>
            <dd class="text-muted">
                原定两周检测方案为韩国SD（4代）试纸，但是在一段时间的使用中发现，两周检测误差较大，艾滋病检测抗体的生成因人而异，有些人在两周
                无法产生足够的抗体，导致检测失败，所以不推荐两周测试。同时在医院和疾控中心，对于高危两周的病人，同样不予检测，因此两周检测方案
                撤销。
            </dd>
        </dl>
    </div>
{% endblock %}

aids_jiance/templates/shizhi/intro.html
{% extends 'layout.html' %}
{% load fangan %}

{% block main %}
  <nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">首页</a></li>
      <li class="breadcrumb-item"><a href="{% url 'shizhi' %}">试纸</a></li>
      {#    <li class="breadcrumb-item"><a href="{% url 'article:article_list' slug=category.slug %}">{{ category.name }}</a></li>#}
      <li class="breadcrumb-item active" aria-current="page">{{ object.name }} 介绍</li>
    </ol>
  </nav>

    <div class="bg-white p-2">
      <a class="red_a text-danger d-block" href="{% url 'shiyong' %}">(点击查看{{ object.name }}使用说明)</a>
      <a class="red_a text-danger d-block" href="{{ object.get_questions_url }}">(点击查看{{ object.name }}网友使用问答)</a>

        <div class="row mt-2">
            <div class="col-md-4">
                <img class="img-fluid" src="{{ object.cover.url }}" alt="{{ object.name }}">
                <p class="text-center">
                    <a class="text-danger" href="{% url 'help' %}">点击购买试纸</a>
                </p>
            </div>
            <div class="col-md-8">{{ object.description|safe }}</div>
        </div>

    </div>

{% endblock %}


{% block rightbar %}
    {% for k, v in fangan %}
        {% fangan_list k v %}
    {% endfor %}
{% endblock %}

aids_jiance/templates/shizhi/questions.html
{% extends 'layout.html' %}
{% load pagination %}
{% block main %}



  <nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">首页</a></li>
      <li class="breadcrumb-item"><a href="{{ shizhi.get_questions_url }}">{{ shizhi.name }}问答</a></li>
      <li class="breadcrumb-item active" aria-current="page">第{{ page_obj.number }}页</li>
    </ol>
  </nav>


  {% include 'core/list.html' %}


{% endblock %}